import { AfterViewInit, Component, ViewChild, inject } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { MatPaginatorModule } from '@angular/material/paginator';
import { TpPaginatorDirective } from '../../../shared/directive/tp-paginator.directive';
import { Pilgrim } from '../../../shared/types/base.type';
import { Store } from '@ngrx/store';
import { PilgrimState } from '../../utils/types/pilgrim.type';
import { selectPilgrims } from '../../data-access/store/pilgrim.reducer';

@Component({
  selector: 'tp-pilgrims-data-table',
  standalone: true,
  imports: [MatPaginatorModule, MatTableModule, TpPaginatorDirective],
  templateUrl: './pilgrims-data-table.component.html',
  styleUrl: './pilgrims-data-table.component.scss',
})
export class PilgrimsDataTableComponent implements AfterViewInit {
  private store = inject(Store<{ pilgrims: PilgrimState }>);
  pilgrims$ = this.store.select(selectPilgrims);
  ngAfterViewInit(): void {
    this.dataSource.paginator = this.paginator;
  }
  // dataSource!: MatTableDataSource<any>;

  @ViewChild(MatPaginator) paginator!: MatPaginator;

  displayedColumns: string[] = [
    'id',
    'name',
    'phone_number',
    'package_name',
    'package_number',
    'arafah_accommodation',
  ];
  dataSource = new MatTableDataSource<Pilgrim>(pilgrims);
}

const pilgrims = [
  {
    id: '1',
    mina_tent_accommodation: 'tent1',
    bus_accommodation: 'bus1',
    national_id: '1234567890',
    permit_status: 'approved',
    name: 'John Doe',
    is_male: true,
    nationality: 'USA',
    phone_number: '+1234567890',
    status: true,
    booking_reference: 'ABC123',
    package_name: 'Standard Package',
    package_number: '1',
    transportation: 'Bus',
    date_of_birth: '1990-01-01',
    date_of_birth_hijri: '1400-01-01',
    city: 'New York',
    code: 'NY',
    mina_building_accommodation: 'building1',
    arafah_accommodation: 'tentArafah1',
  },
  {
    id: '2',
    mina_tent_accommodation: 'tent2',
    bus_accommodation: 'bus2',
    national_id: '0987654321',
    permit_status: 'approved',
    name: 'Jane Smith',
    is_male: false,
    nationality: 'UK',
    phone_number: '+447123456789',
    status: true,
    booking_reference: 'DEF456',
    package_name: 'Premium Package',
    package_number: '2',
    transportation: 'Private Car',
    date_of_birth: '1985-05-15',
    date_of_birth_hijri: '1390-08-25',
    city: 'London',
    code: 'LDN',
    mina_building_accommodation: 'building2',
    arafah_accommodation: 'tentArafah2',
  },
  {
    id: '3',
    mina_tent_accommodation: 'tent3',
    bus_accommodation: 'bus3',
    national_id: '246813579',
    permit_status: 'approved',
    name: 'Ahmed Hassan',
    is_male: true,
    nationality: 'Egypt',
    phone_number: '+201234567890',
    status: true,
    booking_reference: 'GHI789',
    package_name: 'Economy Package',
    package_number: '3',
    transportation: 'Airplane',
    date_of_birth: '1980-07-20',
    date_of_birth_hijri: '1400-12-05',
    city: 'Cairo',
    code: 'CAI',
    mina_building_accommodation: 'building3',
    arafah_accommodation: 'tentArafah3',
  },
  {
    id: '4',
    mina_tent_accommodation: 'tent4',
    bus_accommodation: 'bus4',
    national_id: '135792468',
    permit_status: 'approved',
    name: 'Fatima Ali',
    is_male: false,
    nationality: 'Pakistan',
    phone_number: '+923001234567',
    status: true,
    booking_reference: 'JKL012',
    package_name: 'Standard Package',
    package_number: '4',
    transportation: 'Bus',
    date_of_birth: '1975-03-10',
    date_of_birth_hijri: '1396-07-20',
    city: 'Lahore',
    code: 'LHE',
    mina_building_accommodation: 'building4',
    arafah_accommodation: 'tentArafah4',
  },
  {
    id: '5',
    mina_tent_accommodation: 'tent5',
    bus_accommodation: 'bus5',
    national_id: '987654321',
    permit_status: 'pending',
    name: 'Maria Garcia',
    is_male: false,
    nationality: 'Spain',
    phone_number: '+34123456789',
    status: false,
    booking_reference: 'MNO345',
    package_name: 'Premium Package',
    package_number: '5',
    transportation: 'Private Car',
    date_of_birth: '1995-11-30',
    date_of_birth_hijri: '1416-03-15',
    city: 'Madrid',
    code: 'MAD',
    mina_building_accommodation: 'building5',
    arafah_accommodation: 'tentArafah5',
  },
  {
    id: '6',
    mina_tent_accommodation: 'tent6',
    bus_accommodation: 'bus6',
    national_id: '654321987',
    permit_status: 'approved',
    name: 'Mohammad Khan',
    is_male: true,
    nationality: 'India',
    phone_number: '+919876543210',
    status: true,
    booking_reference: 'PQR678',
    package_name: 'Economy Package',
    package_number: '6',
    transportation: 'Train',
    date_of_birth: '1988-04-25',
    date_of_birth_hijri: '1407-10-10',
    city: 'Mumbai',
    code: 'BOM',
    mina_building_accommodation: 'building6',
    arafah_accommodation: 'tentArafah6',
  },
  {
    id: '7',
    mina_tent_accommodation: 'tent7',
    bus_accommodation: 'bus7',
    national_id: '543216789',
    permit_status: 'rejected',
    name: 'Lina Al-Masri',
    is_male: false,
    nationality: 'Lebanon',
    phone_number: '+9611234567',
    status: false,
    booking_reference: 'STU901',
    package_name: 'Standard Package',
    package_number: '7',
    transportation: 'Bus',
    date_of_birth: '1992-09-15',
    date_of_birth_hijri: '1413-02-02',
    city: 'Beirut',
    code: 'BEY',
    mina_building_accommodation: 'building7',
    arafah_accommodation: 'tentArafah7',
  },
  {
    id: '8',
    mina_tent_accommodation: 'tent8',
    bus_accommodation: 'bus8',
    national_id: '987654123',
    permit_status: 'approved',
    name: 'Ali Ahmed',
    is_male: true,
    nationality: 'Saudi Arabia',
    phone_number: '+966112345678',
    status: true,
    booking_reference: 'VWX234',
    package_name: 'Premium Package',
    package_number: '8',
    transportation: 'Private Car',
    date_of_birth: '1970-12-05',
    date_of_birth_hijri: '1392-04-20',
    city: 'Riyadh',
    code: 'RUH',
    mina_building_accommodation: 'building8',
    arafah_accommodation: 'tentArafah8',
  },
  {
    id: '9',
    mina_tent_accommodation: 'tent9',
    bus_accommodation: 'bus9',
    national_id: '456789123',
    permit_status: 'pending',
    name: 'Sara Abbas',
    is_male: false,
    nationality: 'Iraq',
    phone_number: '+9647812345678',
    status: false,
    booking_reference: 'YZA345',
    package_name: 'Economy Package',
    package_number: '9',
    transportation: 'Bus',
    date_of_birth: '1983-02-20',
    date_of_birth_hijri: '1402-08-10',
    city: 'Baghdad',
    code: 'BGD',
    mina_building_accommodation: 'building9',
    arafah_accommodation: 'tentArafah9',
  },
  {
    id: '10',
    mina_tent_accommodation: 'tent10',
    bus_accommodation: 'bus10',
    national_id: '321654987',
    permit_status: 'approved',
    name: 'Youssef Mahmoud',
    is_male: true,
    nationality: 'Egypt',
    phone_number: '+201012345678',
    status: true,
    booking_reference: 'BCD567',
    package_name: 'Standard Package',
    package_number: '10',
    transportation: 'Train',
    date_of_birth: '1978-06-10',
    date_of_birth_hijri: '1397-10-25',
    city: 'Alexandria',
    code: 'ALY',
    mina_building_accommodation: 'building10',
    arafah_accommodation: 'tentArafah10',
  },
  {
    id: '11',
    mina_tent_accommodation: 'tent10',
    bus_accommodation: 'bus10',
    national_id: '321654987',
    permit_status: 'approved',
    name: 'Youssef Saleh',
    is_male: true,
    nationality: 'Egypt',
    phone_number: '+201012345678',
    status: true,
    booking_reference: 'BCD567',
    package_name: 'Standard Package',
    package_number: '10',
    transportation: 'Train',
    date_of_birth: '1978-06-10',
    date_of_birth_hijri: '1397-10-25',
    city: 'Alexandria',
    code: 'ALY',
    mina_building_accommodation: 'building10',
    arafah_accommodation: 'tentArafah10',
  },
];
